apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-local-volume-pvc
  annotations:
    volumeType: hostPath
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi